config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do 
  	resources :comments, except: [:show, :index]
  end
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations",
  									omniauth_callbacks: "omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
      post :mark_as_unread
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  root 'posts#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post

	validates_presence_of :comment
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :can_not_edit_other_comments, only: [:edit, :update, :destroy]
  before_action :set_post
  before_action :authenticate_user!, notice: 'Sorry, please sign in first!'
  before_action :have_to_have_profile, only: [:new, :create]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.build(comment_params)
    @comment.post_id = @post.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
        format.js
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @post, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to @post, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    def can_not_edit_other_comments
      if @comment.user_id != current_user.id
        redirect_to @post, notice: 'Sorry, you are not the author of this comment.'
      end
    end

    def have_to_have_profile
      if current_user.profile == nil
        redirect_to @post, notice: 'Sorry, please create a profile to comment.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<li class="media">
  <div class="comment">
    <a href="#" class="pull-left">
    <%= image_tag comment.user.profile.profile_pic.url(:thumb), :class => "img-circle"%>
    </a>
    <div class="media-body">
      <strong class="text-success"><%= link_to comment.user.profile.first_name + " " + comment.user.profile.last_name, profile_path(comment.user.profile) %></strong>
      <span class="text-muted">
      <small class="text-muted"><%= time_ago_in_words(comment.created_at) + " ago"%></small>
      </span>
      <span class="text-muted pull-right">
      <% if user_signed_in? && comment.user_id == current_user.id %>
        <small class="btn btn-info btn-xs"><i class="fa fa-times"></i><%= link_to "Edit", edit_post_comment_path(@post, comment) %></small>
        <small class="btn btn-danger btn-xs"><i class="fa fa-times"></i><%= link_to "Remove", post_comment_path(@post, comment), :method => :delete, data: {confirm: "Are you sure?"} %></small>
      <% end %>
      </span>
      <p><%= comment.comment %></p>
    </div>
    <div class="clearfix"></div>
  </div>
</li>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
	<%= f.text_area :comment, class: "form-control new_comment", placeholder: "Write your comment", rows: "5"  %>
	<br>
	<%= f.submit 'Submit comment', :class => "btn btn-info pull-right" %>
<% end %>

app/views/comments/create.js.erb
$('#post_comments').prepend('<%= j render 'comment', comment: @comment %>');
$('.new_comment').val('');

app/views/comments/edit.html.erb
<div class="container">
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>


<%= link_to 'Back', post_path(@comment.post), class: "btn btn-default" %>
</div>