config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do 
  	resources :comments, except: [:show, :index]
  end
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations",
  									omniauth_callbacks: "omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
      post :mark_as_unread
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  root 'posts#index'
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  def index
    if @box.eql? "inbox"
      @conversations = @mailbox.inbox
    elsif @box.eql? "sent"
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end

    @conversations = @conversations.paginate(page: params[:page], per_page: 10)
  end

  def show
    
  end

  def mark_as_read
    @conversation.mark_as_read(current_user)
    flash[:success] = 'The conversation was marked as read.'
    redirect_to conversations_path
  end

  def mark_as_unread
    @conversation.mark_as_unread(current_user)
    flash[:success] = 'The conversation was marked as unread.'
    redirect_to conversations_path
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:body])
    flash[:success] = 'Reply sent'
    redirect_to conversation_path(@conversation)
  end

  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    redirect_to conversations_path
  end

  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    redirect_to conversations_path
  end

  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  private

  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end



  def get_box
    if params[:box].blank? or !["inbox","sent","trash"].include?(params[:box])
      params[:box] = 'inbox'
    end
    @box = params[:box]
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += ' active' if title.downcase == current_box
    content_tag :li, link_to(title.capitalize, conversations_path(box: title.downcase)), opts
  end
end

app/views/conversations/_conversation.html.erb
<li>
  <div class="row">
  <div class="col-sm-9">
    <span class="mail">
  <%= link_to conversation_path(conversation) do %>
    <span class="mail-subject"><%= conversation.subject %>
    </span>
    <span class="mail-message-preview"><%= conversation.last_message.body %><br><small><span class="text-muted"><%= time_ago_in_words(conversation.last_message.created_at) %> ago</span></small>
    </span>
  <% end %>
</span>
  </div>
  <div class="col-sm-3">
    <div class="btn-group-vertical pull-right">
    <% if conversation.is_trashed?(current_user) %>
        <%= link_to 'Restore', restore_conversation_path(conversation), class: 'btn btn-xs btn-info pull-right', method: :post %><br>
      <% else %>
        <p><%= link_to 'Move to trash', conversation_path(conversation), class: 'btn btn-xs btn-danger pull-right', method: :delete, data: {confirm: 'Are you sure?'} %></p><br>
        <% if conversation.is_unread?(current_user) %>
          <%= link_to 'Mark as read', mark_as_read_conversation_path(conversation),
                      class: 'btn btn-xs btn-info pull-right', method: :post %>
        <% else %>
          <%= link_to 'Mark as unread', mark_as_unread_conversation_path(conversation),
                      class: 'btn btn-xs btn-info pull-right', method: :post %>
        <% end %>
      <% end %>
    </div>
  </div>
  </div>
</li>

app/views/conversations/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3">
      <%= link_to new_message_path, class: 'btn btn-info navbar-btn' do %>
        <span class="glyphicon glyphicon-pencil"></span> Compose
      <% end %>
      <ul class="nav nav-pills nav-stacked">
        <%= mailbox_section 'inbox', @box %>
        <%= mailbox_section 'sent', @box %>
        <%= mailbox_section 'trash', @box %>
      </ul>
    </div>

    <div class="col-sm-9">
      <div class="tab-content">
        <% if @box == 'inbox' %>
          <div class="tab-pane active" id="inbox">
            <div class="container">
              <div class="content-container clearfix">
               <div class="col-md-9">
                   <h1 class="content-title">Inbox</h1>

                   <input type="search" placeholder="Search Mail" class="form-control mail-search" />

                   <ul class="mail-list">
                       <%= render partial: 'conversations/conversation', collection: @conversations %>
                       <%= will_paginate %>
                   </ul>
               </div>
              </div>
            </div>
          </div>

        <% elsif @box == 'sent' %>
          <div class="tab-pane active" id="sent-mail">
            <div class="container">
               <div class="content-container clearfix">
                   <div class="col-md-9">
                       <h1 class="content-title">Sent Mail</h1>

                       <input type="search" placeholder="Search Mail" class="form-control mail-search" />

                       <ul class="mail-list">
                        <%= render partial: 'conversations/conversation', collection: @conversations %>
                        <%= will_paginate %>
                       </ul>
                   </div>
               </div>
             </div>
          </div>

        <% elsif @box == 'trash' %>
          <div class="tab-pane active" id="trash">
            <div class="container">
                 <div class="content-container clearfix">
                     <div class="col-md-9">
                         <h1 class="content-title">Trash</h1>
                         <p><%= link_to 'Empty trash', empty_trash_conversations_path, class: 'btn btn-danger pull-right', method: :delete, data: {confirm: 'Are you sure?'} %></p>
                          </br>
                         <input type="search" placeholder="Search Mail" class="form-control mail-search" />

                         <ul class="mail-list">
                          <%= render partial: 'conversations/conversation', collection: @conversations %>
                          <%= will_paginate %>
                         </ul>
                     </div>
                 </div>
             </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/conversations/show.html.erb
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
    <div class="col-md-9 col-md-offset-2">
        <div class="panel">
          <!--Heading-->
        <div class="panel-heading">
          <h3 class="panel-title">
            Subject: <%= @conversation.subject %>
          </h3>
        </div>
        
    
        <!--Widget body-->
        <div id="demo-chat-body" class="collapse in">
          <div class="nano has-scrollbar" style="height:550px">
            <div class="nano-content pad-all" tabindex="0" style="right: -17px;">
              <ul class="list-unstyled media-block">
                <% @conversation.receipts_for(current_user).each do |receipt| %>
                  <% message = receipt.message %>
                  <% if message.sender.id != current_user.id %>
                    <li class="mar-btm">
                      <div class="media-left">
                        <%= image_tag message.sender.profile.profile_pic.url(:thumb), :class => "img-circle img-sm"%>
                      </div>
                      <div class="media-body pad-hor">
                        <div class="speech">
                          <%= link_to message.sender.profile.first_name + " " + message.sender.profile.last_name, message.sender.profile, class: "media-heading" %>
                          <p><%= message.body %></p>
                          <p class="speech-time">
                          <i class="fa fa-clock-o fa-fw"></i><%= message.created_at.strftime("%I:%M%p on %m/%d/%Y") %>
                          </p>
                        </div>
                      </div>
                    </li>
                  <% else %>
                    <li class="mar-btm">
                      <div class="media-right">
                        <%= image_tag message.sender.profile.profile_pic.url(:thumb), :class => "img-circle img-sm"%>
                      </div>
                      <div class="media-body pad-hor speech-right">
                        <div class="speech">
                          <%= link_to message.sender.profile.first_name + " " + message.sender.profile.last_name, message.sender.profile, class: "media-heading" %>
                          <p><%= message.body %></p>
                          <p class="speech-time">
                          <i class="fa fa-clock-o fa-fw"></i><%= message.created_at.strftime("%I:%M%p on %m/%d/%Y") %>
                          </p>
                        </div>
                      </div>
                    </li>
                  <% end %>
                <% end %>
              </ul>
            </div>
          <div class="nano-pane"><div class="nano-slider" style="height: 141px; transform: translate(0px, 0px);"></div></div></div>
    
          <!--Widget footer-->
          <div class="panel-footer">
            <div class="row">
              <%= form_tag reply_conversation_path(@conversation), method: :post do %>
              <div class="col-xs-9">
                <%= text_area_tag 'body', nil, class: 'form-control chat-input', placeholder: 'Type something...', required: true %>
              </div>
              <div class="col-xs-3">
                <%= submit_tag "Send", class: 'btn btn-primary btn-block' %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>