config/routes.rb
Rails.application.routes.draw do
  
  resources :posts do 
  	resources :comments, except: [:show, :index]
  end
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations",
  									omniauth_callbacks: "omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
      post :mark_as_unread
    end
    collection do
      delete :empty_trash
    end
  end
  resources :messages, only: [:new, :create]

  root 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments
	has_and_belongs_to_many :categories

	validates_presence_of :title
	validates_presence_of :body

	# geocoded_by :ip_address,
 #  		:latitude => :lat, :longitude => :lon
	# after_validation :geocode
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :can_not_change_other_posts]
  before_action :can_not_change_other_posts, except: [:new, :create, :index, :show]
  before_action :require_profile, except: [:index, :show]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 12).order("created_at DESC")
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = Comment.where(post_id: @post.id).paginate(:page => params[:page], :per_page => 8).order("created_at DESC")
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.js
        
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :category_ids => [])
    end

    def require_profile
      if user_signed_in? && current_user.profile == nil
        redirect_to new_profile_path, notice: "Please create a profile in order to continue."
      end
    end

    def can_not_change_other_posts
      if user_signed_in? && current_user.id != @post.user_id
        redirect_to post_path(@post), notice: "Sorry, you do not have the permission."
      end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for post do |f| %>
  
<div class="container">
  <div class="well"> 
    <form class="form-horizontal" role="form">
      <h4>What's New</h4>
      <div class="form-group" style="padding:10px;">
        <%= f.input :title, :placeholder => "Title" %>
        </br>
        <%= f.input :body, :input_html => {:rows => 10, :placeholder => "Body"} %>
        </br>
        <%= f.association :categories,
                  collection: Category.all,
                  include_blank: true,
                  input_html: { class: 'chosen-select form-control' } %>
      </div>
      <div>
        <%= f.button :submit, :class=>"btn btn-primary pull-right" %>
        <%= link_to "Cancel", posts_path, class: "btn btn-default pull-right" %>
      </div>
      <ul class="list-inline"><li><a href=""><i class="glyphicon glyphicon-upload"></i></a></li><li><a href=""><i class="glyphicon glyphicon-camera"></i></a></li><li><a href=""><i class="glyphicon glyphicon-map-marker"></i></a></li></ul>
    </form>
  </div>
</div>

<% end %>

app/views/posts/_post.html.erb
  <div class="row">
      <% if posts[0] != nil %>
        <div class="col-md-6 margin-btm-20">
            <div class="quote dark_blue">
              <%= link_to posts[0], style: "text-decoration: none;" do %>
                <blockquote>
                  <p>
                    <%= posts[0].title %>   
                  </p>
                </blockquote>
              <% end %>                    
            </div>
            <div class="quote-footer text-right">
                <div class="quote-author-img">
                  <%= link_to profile_path(posts[0].user.profile) do %>
                    <%= image_tag posts[0].user.profile.profile_pic.url(:thumb), :class => "img-circle"%>
                  <% end %>
                </div>
                <h4><small class="text-muted"><%= time_ago_in_words(posts[0].created_at) +" ago"%> by <%= link_to posts[0].user.profile.first_name, profile_path(posts[0].user.profile.id) %></small>
                </h4>
                <p>
                  <h4>
                    <% posts[0].categories.each do |category| %>
                      <%= link_to category.name, category, :class => "btn btn-xs btn-info" %>
                    <% end %>
                  </h4>
                </p>
            </div>
        </div><!--colored quote box col-->

      <% end %>
      <% if posts[1] != nil %>
        <div class="col-md-6 margin-btm-20">
            <div class="quote blue">
              <%= link_to posts[1], style: "text-decoration: none;" do %>
                <blockquote>
                  <p>
                    <%= posts[1].title %>   
                  </p>
                </blockquote>
              <% end %>                        
            </div>
            <div class="quote-footer text-right">
                <div class="quote-author-img">
                  <%= link_to profile_path(posts[1].user.profile) do %>
                    <%= image_tag posts[1].user.profile.profile_pic.url(:thumb), :class => "img-circle"%>
                  <% end %>
                </div>
                <h4><small class="text-muted"><%= time_ago_in_words(posts[1].created_at) +" ago"%> by <%= link_to posts[1].user.profile.first_name, profile_path(posts[1].user.profile.id) %></small>
                </h4>
                <p>
                  <h4>
                    <% posts[1].categories.each do |category| %>
                      <%= link_to category.name, category, :class => "btn btn-xs btn-info" %>
                    <% end %>
                  </h4>
                </p>
            </div>
        </div><!--colored quote box col-->
        <div class="row divider">    
          <div class="col-sm-12"><hr></div>
        </div> 
      <% end %>
      <% if posts[2] != nil %>
        <div class="col-md-6 margin-btm-20">
            <div class="quote less_gray">
              <%= link_to posts[2], style: "text-decoration: none;" do %>
                <blockquote>
                  <p>
                    <%= posts[2].title %>   
                  </p>
                </blockquote>
              <% end %>                        
            </div>
            <div class="quote-footer text-right">
                <div class="quote-author-img">
                  <%= link_to profile_path(posts[2].user.profile) do %>
                    <%= image_tag posts[2].user.profile.profile_pic.url(:thumb), :class => "img-circle"%>
                  <% end %>
                </div>
                <h4><small class="text-muted"><%= time_ago_in_words(posts[2].created_at) +" ago"%> by <%= link_to posts[2].user.profile.first_name, profile_path(posts[2].user.profile.id) %></small>
                </h4>
                <p>
                  <h4>
                    <% posts[2].categories.each do |category| %>
                      <%= link_to category.name, category, :class => "btn btn-xs btn-info" %>
                    <% end %>
                  </h4>
                </p>
            </div>
        </div><!--colored quote box col-->     
      <% end %>
      <% if posts[3] != nil %>
        <div class="col-md-6 margin-btm-20">
            <div class="quote gray">
              <%= link_to posts[3], style: "text-decoration: none;" do %>
                <blockquote>
                  <p>
                    <%= posts[3].title %>   
                  </p>
                </blockquote>
              <% end %>                        
            </div>
            <div class="quote-footer text-right">
                <div class="quote-author-img">
                  <%= link_to profile_path(posts[3].user.profile) do %>
                    <%= image_tag posts[3].user.profile.profile_pic.url(:thumb), :class => "img-circle"%>
                  <% end %>
                </div>
                <h4><small class="text-muted"><%= time_ago_in_words(posts[3].created_at) +" ago"%> by <%= link_to posts[3].user.profile.first_name, profile_path(posts[3].user.profile.id) %></small>
                </h4>
                <p>
                  <h4>
                    <% posts[3].categories.each do |category| %>
                      <%= link_to category.name, category, :class => "btn btn-xs btn-info" %>
                    <% end %>
                  </h4>
                </p>
            </div>
        </div><!--colored quote box col-->
        <div class="row divider">    
          <div class="col-sm-12"><hr></div>
        </div> 
      <% end %>
  </div><!--testimonials row-->

app/views/posts/edit.html.erb
<%= render 'form', post: @post%>

app/views/posts/index.html.erb
<div class="container">
    <ul>
        <% @posts.each_slice(4) do |posts| %>
          <%= render 'post', posts: posts %>
        <% end %>  
      	<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
    </ul>
</div>
  

app/views/posts/new.html.erb
<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="box">
            <div class="box-icon">
                <span class="fa fa-4x fa-html5"><%= image_tag @post.user.profile.profile_pic.url(:thumb), :class => "img-circle"%></span>
            </div>
            <div class="info">
                <h4 class="text-center"><%= @post.title %></h4>
                <p><%= @post.body %></p>
                <% unless user_signed_in? && @post.user_id == current_user.id %>
                  <%= link_to "Visit " + @post.user.profile.first_name + "'s profile", profile_path(@post.user.profile), class: "btn btn-info" %>
                <% else %>
                  <%= link_to "Edit Post", edit_post_path(@post), class: "btn btn-info" %> 
                  <%= link_to "Delete Post", post_path(@post), :method => :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
                <% end %>
            </div>
        </div>
      </div>
	</div>

  </br>

  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-info">
        <div class="panel-heading">
          Comments (<%= @post.comments.size %>)
        </div>
        <div class="panel-body comments">
          <%= form_for [@post, @comment], remote: true do |f| %>
          	<%= f.text_area :comment, class: "form-control new_comment", placeholder: "Write your comment", rows: "5"  %>
          	<br>
          	<%= f.submit 'Submit comment', :class => "btn btn-info pull-right" %>
          <% end %>
          <div class="clearfix"></div>
          <hr>
          <ul class="media-list" id="post_comments">
            <% @comments.each do |comment| %>
            	<%= render 'comments/comment', comment: comment %>
            <% end %>
            <%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>